### ISSUE TITLE
Can we use the aca_status_flags or mult_star_flag for trending?

### ISSUE THREAD

**Issue by taldcroft** [sot/attitude_error_mon#2]
There are already two places to look for tools / software related to mult stars.  Maybe we don't need a third?

**Comment by taldcroft** [comment]
The plots we are going to be looking at (one shots, attitude errors) will soon be evaluated more in the context of "is a higher planning limit OK?" and not "is multiple stars flag OK?".  In other words, the "msf" part is going to be ancient history in a year because we are _very_ unlikely to go back to MSF enabled.

**Comment by jeanconn** [comment]
Once I've got a Makefile and a task_schedule, it just seems like a different stand-alone project.

**Comment by jeanconn** [comment]
Because we were still comparing two populations (msf enabled vs msf disabled) it still seemed reasonable to have the repo named something like msf_trending even if the msf part will eventually be ancient history.  It seems like at that ancient history time, it will be reasonable to just spin off an att_err_trending project that doesn't know anything about the msf flag.

**Comment by taldcroft** [comment]
Not a huge fan of planned obsolescence (expecting to abandon a project), but as a compromise what about renaming `msf_trending` into meaningful words `mult_stars_flag_trending`, and then swapping a `_` to a `/` so that the trending app becomes `mult_stars_flag/trending`.

**Comment by jeanconn** [comment]
Project renamed attitude_error_mon per in-person discussion.
